name: matan
description: Personalized and opioniated Dart settings and extensions.
version: 2.0.0-dev
homepage: https://github.com/matanlurey/matan.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  coverage: ^1.3.2
  test: ^1.21.1

dependencies:
  meta: ^1.8.0
