name: matan
description: Personalized Dart settings and extensions.
version: 1.0.0
homepage: https://github.com/matanluery/matan.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  coverage: ^1.3.2
  test: ^1.21.1
