name: Dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Install Dependencies
        run: dart pub get

      - name: Dart Format
        run: dart format --output=none --set-exit-if-changed .

      - name: Dart Analyzer
        run: dart analyze --fatal-warnings

      - name: Test
        run: dart run coverage:test_with_coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
          verbose: true
