name: Dart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Install Dependencies
        run: dart pub get

      - name: Dart Format
        run: dart format --output=none --set-exit-if-changed .

      - name: Dart Analyzer
        run: dart analyze --fatal-warnings

      - name: Test
        run: dart run coverage:test_with_coverage

      - name: Upload Coverage
        run: curl -s https://codecov.io/bash
        shell: bash
